name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

env:
  PLUGIN_NAME: typing-assistant

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Build
        id: build
        run: |
          yarn install
          yarn build
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          ls

      - name: Create or update release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          RELEASE_TAG: ${{ github.ref_name }}
        run: |
          if ! gh release view "$RELEASE_TAG" > /dev/null; then
            gh release create "$RELEASE_TAG" --verify-tag --title "$RELEASE_TAG" --notes ""
          fi
          mv "$PLUGIN_NAME.zip" "$PLUGIN_NAME-$RELEASE_TAG.zip"
          gh release upload "$RELEASE_TAG" \
            "$PLUGIN_NAME-$RELEASE_TAG.zip" \
            main.js manifest.json styles.css \
            --clobber
